name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: ["timeout", "heartbeat", "periodic"]
        board: ["esp32dev", "uno", "due"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run unit tests
        run: pio test
        working-directory: test
      - name: Compile example ${{ matrix.example }}
        run: platformio ci --lib=src --board=${{ matrix.board }} examples/${{ matrix.example }}
